apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: kretdocker/notification-service:latest
          ports:
            - containerPort: 8100
          env:
            - name: BROKER_URL
              value: tcp://host.minikube.internal:61616
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1