apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-serivce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: kretdocker/order-service:latest
          ports:
            - containerPort: 8300
          env:
            - name: BROKER_URL
              value: tcp://host.minikube.internal:61616
            - name: JDBC_URL
              value: jdbc:postgresql://host.minikube.internal:5432/otus_db?currentSchema=order_service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1