server:
  port: 8000
  servlet:
    context-path: /user

#spring:
#  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/otus_db?currentSchema=user_service
#    username: otus_db_user
#    password: otus_db_password
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        format-sql: true
#
#  liquibase:
#    enabled: true
#    change-log: classpath:liquibase/changelog.xml
#    default-schema: user_service
#    user: otus_db_user
#    password: otus_db_password

user:
  max-count: 1000 # максимально допустимое количество пользователей в приложении
  max-len-param: 255 # максимальное количество символов в параметрах пользователя

security-settings:
  url-white-list:
    /actuator/**,
    /auth,
    /health,
    /register,
    /swagger-ui.html,
    /swagger-ui/**,
    /v3/api-docs/**

management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always

#Logging
logging:
  config: "classpath:logback.xml"
