server:
  port: 8300
  servlet:
    context-path: /order

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/otus_db?currentSchema=order_service
    username: otus_db_user
    password: otus_db_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format-sql: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
    default-schema: order_service
    user: otus_db_user
    password: otus_db_password

order:
  active-mq:
    broker-url: tcp://localhost:61616
    produce-order-topic: ORDER_TOPIC